<script setup lang="ts">
import { ref, computed } from 'vue';
import { Save, RotateCcw, Search, Info } from 'lucide-vue-next';

const props = defineProps<{
  rawProperties: string;
  saving?: boolean;
}>();

const emit = defineEmits(['save']);

const searchQuery = ref('');

// Categories for MC properties
const categories = {
  'General': ['motd', 'level-name', 'gamemode', 'difficulty', 'pvp', 'spawn-protection'],
  'Performance': ['view-distance', 'simulation-distance', 'max-tick-time', 'entity-broadcast-range-percentage'],
  'Network': ['server-port', 'query.port', 'max-players', 'online-mode', 'prevent-proxy-connections'],
  'World Gen': ['level-seed', 'generate-structures', 'allow-nether', 'max-world-size', 'level-type']
};

const parseProperties = (raw: string) => {
  const result: Record<string, string> = {};
  raw.split('\n').forEach(line => {
    if (line.trim() && !line.startsWith('#')) {
      const [key, ...valueParts] = line.split('=');
      if (key) result[key.trim()] = valueParts.join('=').trim();
    }
  });
  return result;
};

const parsedData = ref<Record<string, string>>(parseProperties(props.rawProperties));

const filteredCategories = computed(() => {
  const result: Record<string, string[]> = {};
  Object.entries(categories).forEach(([cat, keys]) => {
    const filteredKeys = keys.filter(k => k.toLowerCase().includes(searchQuery.value.toLowerCase()));
    if (filteredKeys.length > 0) result[cat] = filteredKeys;
  });
  
  // Add uncategorized
  const allKnownKeys = Object.values(categories).flat();
  const unknownKeys = Object.keys(parsedData.value).filter(k => 
    !allKnownKeys.includes(k) && k.toLowerCase().includes(searchQuery.value.toLowerCase())
  );
  if (unknownKeys.length > 0) result['Advanced / Other'] = unknownKeys;
  
  return result;
});

const handleSave = () => {
  let output = "# Generated by MC-SERVER-BACKEND\n";
  Object.entries(parsedData.value).forEach(([key, val]) => {
    output += `${key}=${val}\n`;
  });
  emit('save', output);
};
</script>

<template>
  <div class="space-y-6">
    <div class="flex flex-col md:flex-row justify-between gap-4 items-start md:items-center bg-zinc-900 p-4 border-2 border-zinc-800">
      <div class="relative flex-1 w-full">
        <Search class="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-zinc-500" />
        <input 
          v-model="searchQuery"
          placeholder="Filter properties..."
          class="w-full bg-black border border-zinc-700 py-2 pl-10 pr-4 text-sm font-mono focus:border-emerald-500 outline-none transition-all"
        />
      </div>
      <div class="flex gap-3 w-full md:w-auto">
        <button @click="parsedData = parseProperties(rawProperties)" class="flex-1 md:flex-none px-4 py-2 border border-zinc-700 text-xs font-black uppercase tracking-widest hover:bg-zinc-800 transition-colors flex items-center justify-center gap-2">
          <RotateCcw class="w-3 h-3" /> Reset
        </button>
        <button @click="handleSave" :disabled="saving" class="flex-1 md:flex-none px-6 py-2 bg-emerald-500 text-zinc-950 text-xs font-black uppercase tracking-widest hover:bg-emerald-400 transition-all flex items-center justify-center gap-2 disabled:opacity-50">
          <Save class="w-3 h-3" /> {{ saving ? 'Saving...' : 'Apply Changes' }}
        </button>
      </div>
    </div>

    <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
      <div v-for="(keys, cat) in filteredCategories" :key="cat" class="space-y-4">
        <h4 class="text-[10px] font-black uppercase tracking-[0.3em] text-emerald-500 flex items-center gap-2">
          <span class="w-8 h-[1px] bg-emerald-500/30"></span>
          {{ cat }}
        </h4>
        
        <div class="grid gap-3">
          <div v-for="key in keys" :key="key" class="group bg-zinc-900/50 border border-zinc-800 p-3 hover:border-zinc-700 transition-colors">
            <div class="flex justify-between items-center mb-2">
              <label class="text-[10px] font-mono text-zinc-400 uppercase tracking-tighter">{{ key }}</label>
              <Info class="w-3 h-3 text-zinc-700 group-hover:text-zinc-500 cursor-help" />
            </div>
            
            <input 
              v-if="parsedData[key] !== 'true' && parsedData[key] !== 'false'"
              v-model="parsedData[key]"
              class="w-full bg-black border border-zinc-800 px-3 py-1.5 text-sm font-mono text-zinc-200 focus:border-zinc-500 outline-none transition-all"
            />
            
            <button 
              v-else
              @click="parsedData[key] = parsedData[key] === 'true' ? 'false' : 'true'"
              :class="parsedData[key] === 'true' ? 'border-emerald-500/50 text-emerald-400' : 'border-rose-500/50 text-rose-400'"
              class="w-full border bg-black py-1.5 text-[10px] font-black uppercase tracking-widest transition-all"
            >
              {{ parsedData[key] }}
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
